apiVersion: v1
kind: PersistentVolume
metadata:
  name: elk-pv
  namespace: elk
  creationTimestamp: null
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: elk
    name: elk-pvc
  hostPath:
    path: /tmp
    type: Directory
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elk-pvc
  namespace: elk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi